import React from 'react'


export const metadata = {
    title: ' ورود به پنل مدیریت',
    description: 'Generated by create next app',
}

const SignInLayout = ({ children }) => {

    return (
        <div>{children}</div>
    )
}

export default SignInLayout