"use client"

import { ThemeProvider } from '@mui/material'
import './globals.css'
import { Inter } from 'next/font/google'
import { theme } from '@/mui/theme'
import './font.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'سایت فروشگاهی',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html dir='rtl' lang="fa">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
