import React from 'react'


export const metadata = {
    title: 'پنل ادمین',
    description: 'Generated by create next app',
}

const AdminPanelLayout = ({ children }) => {

    return (
        <div>{children}</div>
    )
}

export default AdminPanelLayout